export const CREATE_ONE_DIAGNOSIS_DEFAULT_SERVICE =
  'CREATE_ONE_DIAGNOSIS_DEFAULT_SERVICE';
export const FIND_DIAGNOSES_DEFAULT_SERVICE = 'FIND_DIAGNOSES_DEFAULT_SERVICE';
export const FIND_ONE_DIAGNOSIS_DEFAULT_SERVICE =
  'FIND_ONE_DIAGNOSIS_DEFAULT_SERVICE';
export const DIAGNOSIS_POSTGRES_REPOSITORY = 'DIAGNOSIS_POSTGRES_REPOSITORY';
export const DIAGNOSIS_V1_ENDPOINT = '/api/v1/diagnoses';
