export const CREATE_ONE_PATIENT_DEFAULT_SERVICE =
  'CREATE_ONE_PATIENT_DEFAULT_SERVICE';
export const CREATE_HISTORIES_DEFAULT_SERVICE =
  'CREATE_HISTORIES_DEFAULT_SERVICE';
export const FIND_PATIENTS_DEFAULT_SERVICE = 'FIND_PATIENTS_DEFAULT_SERVICE';
export const FIND_ONE_PATIENT_DEFAULT_SERVICE =
  'FIND_ONE_PATIENT_DEFAULT_SERVICE';
export const FIND_HISTORIES_DEFAULT_SERVICE = 'FIND_HISTORIES_DEFAULT_SERVICE';
export const PATIENT_POSTGRES_REPOSITORY = 'PATIENT_POSTGRES_REPOSITORY';
export const PATIENT_MIN_BIRTHDAY_DATE = new Date(Date.UTC(1900, 0, 1));
export const PATIENT_V1_ENDPOINT = '/api/v1/patients';
