export const CREATE_ONE_USER_DEFAULT_SERVICE =
  'CREATE_ONE_USER_DEFAULT_SERVICE';
export const FIND_ONE_USER_DEFAULT_SERVICE = 'FIND_ONE_USER_DEFAULT_SERVICE';
export const USER_POSTGRES_REPOSITORY = 'USER_POSTGRES_REPOSITORY';
export const USER_V1_ENDPOINT = '/api/v1/users';
